version: '3.8'
services:
  mariadb:
    image: mariadb:10.3
    container_name: member-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: memberdb
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mariadb:/docker-entrypoint-initdb.d
    restart: unless-stopped
