spring:
  application:
    name: demo
  datasource:
    url: jdbc:mariadb://localhost:3306/memberdb
    username: user
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl      
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: my-very-secret-jwt-key-should-be-long
  token-validity-in-seconds: 3600  # 1시간

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs  