spring:
  application:
    name: demo
  datasource:
    url: jdbc:mariadb://localhost:3306/memberdb
    username: user
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl      
    show-sql: true
    properties:
      hibernate:
        format_sql: true
