spring:
  application:
    name: demo
  datasource:
    url: jdbc:mariadb://localhost:3306/memberdb
    username: user
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
